name: chess
channels:
  - anaconda
  - conda-forge
dependencies:
  - python==3.9.*
  - pip
  - pip:
    - pytest==6.2.*
    - pandas==1.3.*
    - requests==2.26.0
    - dacite==1.6.0
    - click==8.0.3
    - datetime==4.3.*
