name: chess
channels:
  - anaconda
  - conda-forge
dependencies:
  - python==3.9.*
  - pip
  - pip:
    # Jupyter Utils
    - nbdime
    - jupyter
    - jupyterlab
    - pre-commit

    # Data Manipulation
    - pandas==1.3.*
    - pandas_gbq==0.16.*
    - scipy
    - chess

    # Visualisation
    - matplotlib
    - seaborn
    - plotly

    # Testing
    - pytest==6.2.*

    # Misc
    - dacite==1.6.0
    - click==8.0.3
    - datetime==4.3.*
    - black==22.10.0
