name: Deployment
run-name: Deployment triggered by ${{ github.event_name }} from ${{ github.actor }}

on:
  push:
    branches: 
      - "master"

jobs:
  Format:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: chess
          environment-file: environment_basic.yaml

      - name: Format code
        run: make format

      - name: Commit actions changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change from ${{ github.event_name }} to ${{ github.ref }}


  Deploy-and-trigger:
    runs-on: ubuntu-latest

    # needs: Format

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: chess
          environment-file: environment.yaml

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9
      