name: Deployment
run-name: Deployment triggred by ${{ github.event_name }} from ${{ github.actor }}
on:
  push:
    branches: 
      - "master"
jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This action will format the repo."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "🍏 This job's status is ${{ job.status }}."

  Deploy-and-trigger:
    runs-on: ubuntu-latest

    needs: Format

    steps:
      - run: echo "This action will deploy terraform and trigger chess ingestion."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "🍏 This job's status is ${{ job.status }}."